apiVersion: v1
kind: Service
metadata:
  name: app_nodejs_poc-svc
  labels:
    app: app_nodejs_poc
spec:
  type: ClusterIP
  selector:
    app: app_nodejs_poc
  ports:
  - name: app_nodejs_poc-svc-port
    port: 8080
    protocol: TCP
    targetPort: 8080
