apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: CDISCHED
    type: internal-apps-001
  name: uki-bi-app-1-route-testqa
  namespace: ns-uki-bi-app-1-gd-kps-testqa-wus3
spec:
  host: cdi-scheduler-testqa.zkpw3uspriv.app.kyndryl.net
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: uki-bi-app-1-svc
