apiVersion: v1
kind: Service
metadata:
  name: uki-bi-app-nodejs-svc
  labels:
    app: uki-bi-app-nodejs
spec:
  type: ClusterIP
  selector:
    app: uki-bi-app-nodejs
  ports:
  - name: uki-bi-app-nodejs-svc-port
    port: 8080
    protocol: TCP
    targetPort: 8080
