apiVersion: v1
kind: Service
metadata:
  name: uki-bi-app-1-svc
  labels:
    app: uki-bi-app-1
spec:
  type: ClusterIP
  selector:
    app: uki-bi-app-1
  ports:
  - name: uki-bi-app-1-svc-port
    port: 8080
    protocol: TCP
    targetPort: 8080
